services:
    ledgerly:
        build: .
        container_name: ledgerly
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=postgres://serverUser:password@postgres:5432/Finance
            - JWT_SECRET_KEY=02OnN46Yh6s9iDEXL23PfvH3qaZfywNeqib9Oe1b5pQ=
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: serverUser
            POSTGRES_PASSWORD: password
            POSTGRES_DB: Finance
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
