version: "3.9"

services:
    ledgerly:
        image: danmichaeloudis/ledgerly:latest
        container_name: ledgerly
        restart: always
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgres://ledgerly:ledgerly@postgres:5432/ledgerly
            - JWT_SECRET_KEY=02OnN46Yh6s9iDEXL23PfvH3qaZfywNeqib9Oe1b5pQ=
        ports:
            - "3000:3000"
        networks:
            - ledgerly-net
    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ledgerly
            POSTGRES_PASSWORD: ledgerly
            POSTGRES_DB: ledgerly
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ledgerly-net

volumes:
    postgres_data:

networks:
    ledgerly-net:
        driver: bridge
